import type { Student } from './types';

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    brObrasca: '123/I/22/01',
    brojURegistru: '156',
    jmbg: '1505007710001',
    job: '200700001',
    prezime: 'Petrović',
    ime: 'Nikola',
    mestoRodjenja: 'Beograd',
    datumRodjenja: '2007-05-15',
    opstinaRodjenja: 'Savski Venac',
    drzavaRodjenja: 'Srbija',
    imeRoditeljaOca: 'otac',
    imeRoditeljaStaratelja: 'Marko Petrović',
    skolaUpisa: 'Elektrotehnička škola „Nikola Tesla"',
    razredUpisa: 'I',
    obrazovniProfilSmer: 'Elektrotehničar računara',
    jispProgram: '123456',
    trajanjeObrazovanjaGodina: 4,
    razredi: {
      1: {
        skolskaGodina: '2022/2023',
        razred: 'I',
        predmeti: [
          { naziv: 'Srpski jezik i književnost', ocena: '5' },
          { naziv: 'Engleski jezik', ocena: '5' },
          { naziv: 'Matematika', ocena: '4' },
          { naziv: 'Fizika', ocena: '5' },
          { naziv: 'Istorija', ocena: '4' },
          { naziv: 'Geografija', ocena: '4' },
          { naziv: 'Računarstvo i informatika', ocena: '5' },
          { naziv: 'Osnovi elektrotehnike', ocena: '5' },
          { naziv: 'Tehničko crtanje', ocena: '5' },
          { naziv: 'Fizičko vaspitanje', ocena: '5' },
        ],
        vladanje: 'Primerno (5)',
        opstiUspeh: 'Odličan',
        prosecnaOcena: '4.80',
        delovodniBrojIspisnice: '',
        datumIspisnice: '',
        primilaIspisnicu: '',
        delovodniBrojUverenjaPIspit: '',
        datumUverenjaPIspit: '',
        primilaUverenjePIspit: '',
        delovodniBrojSvedocanstva: '2345/2023',
        datumSvedocanstva: '20.06.2023.',
        primiliSvedocanstvo: 'M. Petrović, 21.06.2023.',
        serijskiBrojSvedocanstva: 'SV-001234',
        potpisOdeljenskogStaresine: 'Ana Jović',
      }
    },
    pohvaleINagrade: '',
    matura: {
      tipIspita: 'maturski',
      rokPolaganja: 'junski',
      skolskaGodina: '2025/2026',
      godinaPolaganja: '2026',
      predmetiZnanje: [
        { naziv: 'Srpski jezik i književnost', ocena: '' },
        { naziv: 'Matematika', ocena: '' },
      ],
      datumOdbraneRada: '',
      maturskiRad: {
        nazivRada: '',
        ocenaIzrade: '',
        ocenaOdbrane: '',
        ocenaRada: '',
      },
      ukupnaOcena: '',
      uspeh: '',
      delovodniBrojDiplome: '',
      datumDiplome: '',
      delovodniBrojUverenja: '',
      datumUverenja: '',
      serijskiBrojDiplome: '',
      primilaDispIUverenje: '',
    },
    napomene: '',
  }
];
